---
title: "Untitled"
output: pdf_document
date: "2022-10-29"
---

```{r warning=FALSE}
x1<-c(0.5,1,1.5,2,2.5,3,4.5,5)
x2<-c(0.5,1,1.5,2,2.5,3,4.5,5)
y1<-c(0.0323,0.0667,0.1034,0.1429,0.1852,0.2308,0.3913,0.4545)
y2<- c(0.0256 ,0.0526 ,0.0811 ,0.1111,0.1429,0.1765,0.2903,0.3333)
par(mfrow=c(1,2))
plot(x1,y1, pch = 1,xlab = "Lamda",ylab = "Wq",main="Formula-Up")
plot(x2,y2, pch = 2,xlab = "Lamda",ylab = "Wq",main="Formula -Down")
mtext("Pollaczek Khinchine",side = 3,line = -1,outer = TRUE)
```

```{r }
# heavy two ways

two_ways <- function(lambda_high, lambda_low, lambda_up)
{
  counter <- 0
  n_up <- 0 # number of people up
  n_down <- 0 # number of people down
  l_train <- 0 # how much time passed since the last train
  elevator_state <- 0
  
  train_freq <- 30
  theta <- 1/10 
  state1 <- 1
  
  
  elevator_travel <- 1
  elevator_capacity <- 16
  
  T <- 30
  
  clock <- 0
  
  L_up <- 0 # number of travelers in the system
  L_down <- 0
  avg_lambda_down <- (1/3)*lambda_high + (2/3)*lambda_low
  avg_lambda_up <- lambda_up
  elev_time <- 0
  spe_time <- 0
  last_clock <- 0
  res_up <- rep(NaN, 500)
  res_down <- rep(NaN, 500)
  res_nup <- rep(NaN, 500)
  res_ndown <- rep(NaN,500)
  for (i in 1:500)
  {
    while(clock<T) {
      if(n_up==0 & n_down==0){ #no one
        counter <- counter+1
        time <-rexp(1,lambda_up+lambda_high*state1+ lambda_low*(1-state1)+theta)
        if (clock + time <= elev_time+1 || elev_time==0)
        {
          clock <- clock+time
          spe_time <- 0
        }
        else
        {
          spe_time <- 1
          clock <- elev_time+1
          elevator_state <- elevator_state + 0.5
          elev_time <- 0
        }
        L_up <- L_up + n_up*(clock-last_clock)
        L_down <- L_down + n_down*(clock-last_clock)
        if (spe_time==0 && clock>0)
        {
          up_or_down <- runif(1,0,1)
          if (up_or_down>(avg_lambda_up/(avg_lambda_up+avg_lambda_down)))
          {
            n_down <- n_down + 1
          }
          else
          {
            n_up <- n_up + 1
          }
        }
      } 
      else
      {
        if ((n_down>0) & (n_up>0)) # people in both queues
        {
          if (elevator_state==0)
          {
            if (n_down>=elevator_capacity)
            {
              n_down <- n_down-elevator_capacity
            }
            else
            {
              n_down <- 0
            }
            elevator_state <- 0.5
            elev_time <- clock
            
          }
          else
          {
            if (elevator_state==1)
            {
              if (n_up>=elevator_capacity)
              {
                n_up <- n_up-elevator_capacity
              }
              else
              {
                n_up <- 0
              }
              elevator_state <- -0.5
              elev_time <- clock
            }
          }
        }
        if (n_down==0 & n_up>0) # people only upstairs
        {
          if (elevator_state==1)
          {
            if (n_up>=elevator_capacity)
            {
              n_up <- n_up-elevator_capacity
            }
            else
            {
              n_up <- 0
            }
            elevator_state <- -0.5
            elev_time <- clock
          }
          else
          {
            if (elevator_state==0)
            {
              elevator_state <- 0.5
              elev_time <- clock
            }
          }
          
        }
        if (n_down>0 & n_up==0) # people only downstairs
        {
          if (elevator_state==0)
          {
            if (n_down>=elevator_capacity)
            {
              n_down <- n_down-elevator_capacity
            }
            else
            {
              n_down <- 0
            }        
            elevator_state <- 0.5
            elev_time <- clock
            
          }
          else
          {
            if (elevator_state==1)
            {
              elevator_state <- -0.5
              elev_time <- clock
            }
          }
        }
        time <-rexp(1,lambda_up+lambda_high*state1+ lambda_low*(1-state1)+theta)
        if (clock + time <= elev_time+1 || elev_time==0)
        {
          clock <- clock+time
          spe_time <- 0
        }
        else
        {
          spe_time <- 1
          clock <- elev_time+1
          elevator_state <- elevator_state + 0.5
          elev_time <- 0
        }
        L_up <- L_up + n_up*(clock-last_clock)
        L_down <- L_down + n_down*(clock-last_clock)
        if (spe_time==0 && clock>0)
        {
          up_or_down <- runif(1,0,1)
          if (up_or_down>(avg_lambda_up/(avg_lambda_up+avg_lambda_down)))
          {
            n_down <- n_down + 1
          }
          else
          {
            n_up <- n_up + 1
          }
        }
      }
      last_clock <- clock
    }
    W_up <- (L_up/T)/avg_lambda_up # average waiting time
    W_down <- (L_down/T)/avg_lambda_down
    res_up[i]= W_up
    res_down[i] <- W_down
    res_nup[i] <- n_up
    res_ndown[i] <- n_down
    counter <- 0
    n_up <- 0 # number of people up
    n_down <- 0 # number of people down
    l_train <- 0 # how much time passed since the last train
    elevator_state <- 0
    
    train_freq <- 30
    theta <- 1/10 
    state1 <- 1
    
    elevator_travel <- 1
    elevator_capacity <- 16
    
    T <- 30
    
    clock <- 0
    
    L_up <- 0 # number of travelers in the system
    L_down <- 0
    elev_time <- 0
    spe_time <- 0
    last_clock <- 0
    
    
  }
  
  ret <- c(mean(res_up),mean(res_down), mean(res_nup), mean(res_ndown))
  return (ret)
}


#########################################################################






#########################################################################
#up

up_peak <- function(lambda_high, lambda_low, lambda_up)
{
  counter <- 0
  n_up <- 0 # number of people up
  n_down <- 0 # number of people down
  l_train <- 0 # how much time passed since the last train
  elevator_state <- 0
  
  train_freq <- 30
  theta <- 1/10 
  state1 <- 1
  
  
  elevator_travel <- 1
  elevator_capacity <- 16
  
  T <- 30
  
  clock <- 0
  
  L_up <- 0 # number of travelers in the system
  L_down <- 0
  avg_lambda_down <- (1/3)*lambda_high + (2/3)*lambda_low
  avg_lambda_up <- lambda_up
  elev_time <- 0
  spe_time <- 0
  last_clock <- 0
  res_up <- rep(NaN, 500)
  res_down <- rep(NaN, 500)
  res_nup <- rep(NaN, 500)
  res_ndown <- rep(NaN,500)
  for (i in 1:500)
  {
    while(clock<T) {
      #message ("clock= ",clock)
      #print(elevator_state)
      #print(n_up)
      #print(n_down)
      #print(L_down)
      if(n_up==0 & n_down==0){ #no one
        counter <- counter+1
        time <-rexp(1,lambda_up+lambda_high*state1+ lambda_low*(1-state1)+theta)
        if (clock + time <= elev_time+1 || elev_time==0)
        {
          clock <- clock+time
          spe_time <- 0
        }
        else
        {
          spe_time <- 1
          clock <- elev_time+1
          elevator_state <- elevator_state + 0.5
          elev_time <- 0
        }
        L_up <- L_up + n_up*(clock-last_clock)
        L_down <- L_down + n_down*(clock-last_clock)
        if (spe_time==0 && clock>0)
        {
          up_or_down <- runif(1,0,1)
          if (up_or_down>(avg_lambda_up/(avg_lambda_up+avg_lambda_down)))
          {
            n_down <- n_down + 1
          }
          else
          {
            n_up <- n_up + 1
          }
        }
        if (elevator_state==0)
        {
          elevator_state <- 0.5
          elev_time <- clock
        }
      } 
      else
      {
        if ((n_down>0) & (n_up>0)) # people in both queues
        {
          if (elevator_state==0)
          {
            if (n_down>=elevator_capacity)
            {
              n_down <- n_down-elevator_capacity
            }
            else
            {
              n_down <- 0
            }
            elevator_state <- 0.5
            elev_time <- clock
            
          }
          else
          {
            if (elevator_state==1)
            {
              if (n_up>=elevator_capacity)
              {
                n_up <- n_up-elevator_capacity
              }
              else
              {
                n_up <- 0
              }
              elevator_state <- -0.5
              elev_time <- clock
            }
          }
        }
        if (n_down==0 & n_up>0) # people only upstairs
        {
          if (elevator_state==1)
          {
            if (n_up>=elevator_capacity)
            {
              n_up <- n_up-elevator_capacity
            }
            else
            {
              n_up <- 0
            }
            elevator_state <- -0.5
            elev_time <- clock
          }
          else
          {
            if (elevator_state==0)
            {
              elevator_state <- 0.5
              elev_time <- clock
            }
          }
          
        }
        if (n_down>0 & n_up==0) # people only downstairs
        {
          if (elevator_state==0)
          {
            if (n_down>=elevator_capacity)
            {
              n_down <- n_down-elevator_capacity
            }
            else
            {
              n_down <- 0
            }        
            elevator_state <- 0.5
            elev_time <- clock
            
          }
          else
          {
            if (elevator_state==1)
            {
              elevator_state <- -0.5
              elev_time <- clock
            }
          }
        }
        time <-rexp(1,lambda_up+lambda_high*state1+ lambda_low*(1-state1)+theta)
        if (clock + time <= elev_time+1 || elev_time==0)
        {
          clock <- clock+time
          spe_time <- 0
        }
        else
        {
          spe_time <- 1
          clock <- elev_time+1
          elevator_state <- elevator_state + 0.5
          elev_time <- 0
        }
        L_up <- L_up + n_up*(clock-last_clock)
        L_down <- L_down + n_down*(clock-last_clock)
        if (spe_time==0 && clock>0)
        {
          up_or_down <- runif(1,0,1)
          if (up_or_down>(avg_lambda_up/(avg_lambda_up+avg_lambda_down)))
          {
            n_down <- n_down + 1
          }
          else
          {
            n_up <- n_up + 1
          }
        }
      }
      last_clock <- clock
    }
    W_up <- (L_up/T)/avg_lambda_up # average waiting time
    W_down <- (L_down/T)/avg_lambda_down
    res_up[i]= W_up
    res_down[i] <- W_down
    res_nup[i] <- n_up
    res_ndown[i] <- n_down
    counter <- 0
    n_up <- 0 # number of people up
    n_down <- 0 # number of people down
    l_train <- 0 # how much time passed since the last train
    elevator_state <- 0
    
    train_freq <- 30
    theta <- 1/10 
    state1 <- 1
    elevator_travel <- 1
    elevator_capacity <- 16
    
    T <- 30
    
    clock <- 0
    
    L_up <- 0 # number of travelers in the system
    L_down <- 0
    elev_time <- 0
    spe_time <- 0
    last_clock <- 0
    
    
  }
  
  ret <- c(mean(res_up),mean(res_down),mean(res_nup),mean(res_ndown))
  return (ret)
  
}



###############################################################################



###############################################################################
#Down

down_peak <- function(lambda_high, lambda_low, lambda_up)
{
  counter <- 0
  n_up <- 0 # number of people up
  n_down <- 0 # number of people down
  l_train <- 0 # how much time passed since the last train
  elevator_state <- 0
  
  train_freq <- 30
  theta <- 1/10 
  state1 <- 1
  
  
  elevator_travel <- 1
  elevator_capacity <- 16
  
  T <- 30
  
  clock <- 0
  
  L_up <- 0 # number of travelers in the system
  L_down <- 0
  avg_lambda_down <- (1/3)*lambda_high + (2/3)*lambda_low
  avg_lambda_up <- lambda_up
  elev_time <- 0
  spe_time <- 0
  last_clock <- 0
  res_up <- rep(NaN, 500)
  res_down <- rep(NaN, 500)
  res_nup <- rep(NaN, 500)
  res_ndown <- rep(NaN,500)
  for (i in 1:500)
  {
    while(clock<T) {
      #message ("clock= ",clock)
      #print(elevator_state)
      #print(n_up)
      #print(n_down)
      #print(L_down)
      if(n_up==0 & n_down==0){ #no one
        counter <- counter+1
        time <-rexp(1,lambda_up+lambda_high*state1+ lambda_low*(1-state1)+theta)
        if (clock + time <= elev_time+1 || elev_time==0)
        {
          clock <- clock+time
          spe_time <- 0
        }
        else
        {
          spe_time <- 1
          clock <- elev_time+1
          elevator_state <- elevator_state + 0.5
          elev_time <- 0
        }
        L_up <- L_up + n_up*(clock-last_clock)
        L_down <- L_down + n_down*(clock-last_clock)
        if (spe_time==0 && clock>0)
        {
          up_or_down <- runif(1,0,1)
          if (up_or_down>(avg_lambda_up/(avg_lambda_up+avg_lambda_down)))
          {
            n_down <- n_down + 1
          }
          else
          {
            n_up <- n_up + 1
          }
        }
        if (elevator_state==1)
        {
          elevator_state <- -0.5
          elev_time <- clock
        }
      } 
      else
      {
        if ((n_down>0) & (n_up>0)) # people in both queues
        {
          if (elevator_state==0)
          {
            if (n_down>=elevator_capacity)
            {
              n_down <- n_down-elevator_capacity
            }
            else
            {
              n_down <- 0
            }
            elevator_state <- 0.5
            elev_time <- clock
            
          }
          else
          {
            if (elevator_state==1)
            {
              if (n_up>=elevator_capacity)
              {
                n_up <- n_up-elevator_capacity
              }
              else
              {
                n_up <- 0
              }
              elevator_state <- -0.5
              elev_time <- clock
            }
          }
        }
        if (n_down==0 & n_up>0) # people only upstairs
        {
          if (elevator_state==1)
          {
            if (n_up>=elevator_capacity)
            {
              n_up <- n_up-elevator_capacity
            }
            else
            {
              n_up <- 0
            }
            elevator_state <- -0.5
            elev_time <- clock
          }
          else
          {
            if (elevator_state==0)
            {
              elevator_state <- 0.5
              elev_time <- clock
            }
          }
          
        }
        if (n_down>0 & n_up==0) # people only downstairs
        {
          if (elevator_state==0)
          {
            if (n_down>=elevator_capacity)
            {
              n_down <- n_down-elevator_capacity
            }
            else
            {
              n_down <- 0
            }        
            elevator_state <- 0.5
            elev_time <- clock
            
          }
          else
          {
            if (elevator_state==1)
            {
              elevator_state <- -0.5
              elev_time <- clock
            }
          }
        }
        time <-rexp(1,lambda_up+lambda_high*state1+ lambda_low*(1-state1)+theta)
        if (clock + time <= elev_time+1 || elev_time==0)
        {
          clock <- clock+time
          spe_time <- 0
        }
        else
        {
          spe_time <- 1
          clock <- elev_time+1
          elevator_state <- elevator_state + 0.5
          elev_time <- 0
        }
        L_up <- L_up + n_up*(clock-last_clock)
        L_down <- L_down + n_down*(clock-last_clock)
        if (spe_time==0 && clock>0)
        {
          up_or_down <- runif(1,0,1)
          if (up_or_down>(avg_lambda_up/(avg_lambda_up+avg_lambda_down)))
          {
            n_down <- n_down + 1
          }
          else
          {
            n_up <- n_up + 1
          }
        }
      }
      #breaker <- breaker + 1
      last_clock <- clock
    }
    W_up <- (L_up/T)/avg_lambda_up # average waiting time
    W_down <- (L_down/T)/avg_lambda_down
    res_up[i]= W_up
    res_down[i] <- W_down
    res_nup[i] <- n_up
    res_ndown[i] <- n_down
    counter <- 0
    n_up <- 0 # number of people up
    n_down <- 0 # number of people down
    l_train <- 0 # how much time passed since the last train
    elevator_state <- 0
    
    train_freq <- 30
    theta <- 1/10 
    state1 <- 1
    
    elevator_travel <- 1
    elevator_capacity <- 16
    
    T <- 30
    
    clock <- 0
    
    L_up <- 0 # number of travelers in the system
    L_down <- 0
    elev_time <- 0
    spe_time <- 0
    last_clock <- 0
    
    
  }
  
  
  ret <- c(mean(res_up),mean(res_down),mean(res_nup),mean(res_ndown))
  return (ret)
  
}
c <-c(0.5,1,1.5,2,2.5,3,3.5,4,4.5,5,5.5,6,6.5,7,7.5,8,8.5,9,9.5,10)

matrixxx_1 <- matrix(1:80,ncol=4)
matrixxx_2 <- matrix(1:80,ncol=4)
matrixxx_3 <- matrix(1:80,ncol=4)
lamde_type<-1
for (i in c){
  l_high <- i*1
  l_low <- i*0.1
  l_up <- i*0.5
  a<-c((two_ways(l_high,l_low,l_up)))
  b<-c((up_peak(l_high,l_low,l_up)))
  c<-c((down_peak(l_high,l_low,l_up)))
  for(l in 1:4){
    matrixxx_1[lamde_type,l] <-a[l]
    matrixxx_2[lamde_type,l] <-b[l]
    matrixxx_3[lamde_type,l] <-c[l]
  }
  lamde_type<-lamde_type+1
}
matrix_graph<- function(matrixss,text)
{
X <- c(0.5,1,1.5,2,2.5,3,3.5,4,4.5,5,5.5,6,6.5,7,7.5,8,8.5,9,9.5,10)
Y1 <- matrixss[,1]
Y2 <- matrixss[,2]
Y3 <- matrixss[,3]
Y4 <- matrixss[,4]
par(mfrow=c(2,2))
plot(X,Y1, pch = 1,xlab = "Lamda",ylab = "Waiting up")
plot(X,Y2, pch = 2,xlab = "Lamda",ylab = "Waiting down")
plot(X,Y3, pch = 3,xlab = "Lamda",ylab ="Avg number  in queue up")
plot(X,Y4, pch = 4,xlab = "Lamda",ylab ="Avg number  in queue down")
mtext(text,side = 3,line = -2,outer = TRUE)
}
print("Raw data for the heavy two ways")
print(matrixxx_1)
matrix_graph(matrixxx_1,"Heavy two ways (policy 1)")
print("Raw data for the up peak")
print(matrixxx_2)
matrix_graph(matrixxx_2,"Up peak (policy 2)")
print("Raw data for the down peak")
print(matrixxx_3)
matrix_graph(matrixxx_3,"Down peak (policy 3)")

```


